### PR TITLE
Additional Configurations

### PR DESCRIPTION
**Pull request by MattSurabian**
Support passing in additional configuration for things like GCP unsealing as discussed in Slack

### CODE REVIEW

**Review by stuart-c-moore — APPROVED** [review]
Tested successfully on bosh-lite

**Comment by MattSurabian** [comment]
@migs do you think the naming of the configuration properties in the spec makes sense?

**Comment by stuart-c-moore** [comment]
> @migs do you think the naming of the configuration properties in the spec makes sense?

It did for me, but I did need to do a bit of reverse engineering to work out that I needed to supply a 'name' and 'config' - maybe the spec file could mention that in some way?

Perhaps something like:

```
additional_config.name:
  example: google_credentials.json
  description: A file name containing additional configuration if required, with the above example placed in /var/vcap/jobs/vault/config/google_credentials.json
additional_config.config:
  description: The contents of the above file
```

**Comment by MattSurabian** [comment]
Yeah I thought about this. I was hoping the README would serve the purpose but I think most folks look in the `spec` file so something in there would be good. 

My issue is that this feature implementation supports an array of properties AND the single `additional_config.name` `additional_config.config`. I'm not sure how other bosh releases that support array properties do this in their spec documentation. Maybe just note that it could also be supplied as an array in the case folks need to create multiple additional files?

**Pull request merged**
