### PR TITLE
Allow Google Cloud storage backend to be used

### PR DESCRIPTION
**Pull request by simonjohansson**
Topic \o/

### CODE REVIEW

**Comment by jhunt** [comment]
Is there a particular advantage to using Google Cloud Storage for Vault backends?

**Comment by simonjohansson** [comment]
Well, its less for me to maintain :)

**Comment by jhunt** [comment]
Can you resolve these conflicts?

**Comment by jhunt** [comment]
I apparently don't know how to use the GH conflict resolver.  :/

**Comment by simonjohansson** [comment]
Sure, ill take a look!

**Comment by simonjohansson** [comment]
Rebased to master.

**Comment by jhunt** [comment]
Bloody hell.  All these PRs conflict with each other.  Can you take another crack now that the other PR was merged?

**Comment by simonjohansson** [comment]
@jhunt should be mergable now!

**Comment by jhunt** [comment]
Thanks!

**Pull request merged**
