### PR TITLE
Added bosh2.0 style manifest template

### PR DESCRIPTION
**Pull request by z4ce**
I thought the community might find a bosh2.0 style manifest for vault useful

### CODE REVIEW

**Comment by drnic** [comment]
Can I ask a favour to future proof this? Can it go in `manifests/vault.yml`?

This is the pattern that will be in future bosh-gen for example; and it's where other repos with just bosh2.0 manifests are storing them.

I'm not sure that bosh releases will need/want templates/make_manifest & friends in future.

IMO.

**Comment by drnic** [comment]
@z4ce I hope your ok with me commenting on nearly every little bit of your manifest. It is super cool that you made it. My comments are with love for your contribution and for guiding the community towards consistent "just works on any cloud-config" manifests. Then new users can learn to deploy one thing - say this vault manifest - and they'll know how to deploy any bosh2.0 manifest. Happy times!

**Comment by z4ce** [comment]
Updated the file name to `vault.yml`. Feel free comment or modify as you feel fit!

**Comment by drnic** [comment]
@z4ce I think vault.yml missing

**Comment by z4ce** [comment]
Yeah.. forgot to `git mv` It should be there now

**Comment by drnic** [comment]
@z4ce you ok with some/all of the inline comments (now under "Show outdated")?

**Comment by z4ce** [comment]
@drnic I assume you are referring to comments in the commit section on the PR? Oddly I don't see any comments. Neither outdated nor current.

**Comment by drnic** [comment]
@z4ce ok np; here's the screenshots from my browser:

screen shot 2017-05-13 at 2 21 57 pm

screen shot 2017-05-13 at 2 22 06 pm

screen shot 2017-05-13 at 2 22 11 pm

**Comment by drnic** [comment]
@z4ce thanks for next iteration!

**Comment by zmb3** [comment]
Thanks for this @z4ce - I've been meaning to do this for a while and never got to it.

It would also be great to use bosh2 variables to make this even easier to deploy.

**Comment by z4ce** [comment]
OK I switched from using default types to variables

**Comment by jhunt** [comment]
Thanks!

**Pull request merged**
