### PR TITLE
Updates in telemetry section

### PR DESCRIPTION
**Pull request by paweloczadly**
I moved statsd_addr and statsite_addr to telemetry section in vault job spec and also added disable_hostname parameter.

### CODE REVIEW

**Comment by paweloczadly** [comment]
Does anything block it before merging?

**Comment by norman-abramovitz** [comment]
Not from your side,  We have some ci pipeline issues we need to fix first.

**Comment by jhunt** [comment]
I believe the current regression on CI is because of #b23c3c4 - specifically, the Vault is redirecting to an internal port during the pre-test unseal.  I'll get that patched up today, and then we can merge this.

**Comment by jhunt** [comment]
CI is fixed!  Merging.

**Comment by jhunt** [comment]
Thanks!

**Comment by simonkey007** [comment]
Thanks @jhunt

**Pull request merged**
