### PR TITLE
Allow to use custom storage types

### PR DESCRIPTION
**Pull request by Infra-Red**
Usage example:
```
properties:
  vault:
    storage:
      custom:
        type: zookeeper
        options:
          address: localhost:2181
          path: vault/
```

### CODE REVIEW

**Comment by jhunt** [comment]
I specifically removed the zookeeper storage backend support in d5a09025, and if I had my druthers, I'd remove all of the storage options except file-backed storage.

What is your use case for zookeeper?

**Comment by Infra-Red** [comment]
We're using Zookeeper with non-BOSH deployment and I would like to continue working with Zookeeper backend.

**Comment by jhunt** [comment]
Aside from familiarity, does Zookeeper provide any features above and beyond, something like consul or the file backend?  I'm trying to walk back the complexity of this BOSH release, so that people have fewer decisions they need to make (storage backend being one of those)

**Comment by jhunt** [comment]
Can you resolve these conflicts?

**Review by jhunt — APPROVED** [review]
While I disagree with the wonton addition of even more configuration to this release, I have no technical issues with the implementation.

**Comment by Infra-Red** [comment]
@jhunt I've merged in changes from master and resolved conflicts.

**Pull request merged**
