### PR TITLE
Enable mutual auth between vault and consul backend

### PR DESCRIPTION
**Pull request by atulkc**
This PR adds ability to deploy vault by enabling mutual auth between vault and consul. It provides ability to do following configuration in deployment manifest:
1. Setup TLS parameters for consul backend
2. Setup TLS parameters for listener
3. Setup Vault to use client certificates to authenticate with consul
Consul bosh release has also been modified to support TLS for http apis as part of this [PR](https://github.com/cloudfoundry-community/consul-boshrelease/pull/31)
This PR also adds some missing HA parameters like:
1. redirect_address
2. cluster_address
And adds these to add supported HA backends.

### CODE REVIEW

**Comment by jhunt** [comment]
I haven't forgotten about this PR, I just haven't had sufficient bandwidth to spin up a test deployment to see how it goes.

**Comment by atulkc** [comment]
Attaching manifest file for bosh-lite for your reference. Hope that helps with your testing.

[manifest.zip](https://github.com/cloudfoundry-community/vault-boshrelease/files/556469/manifest.zip)

**Comment by jhunt** [comment]
Can you fix the merge conflicts with master?

**Comment by atulkc** [comment]
I have fixed the merge conflict. Also, I failed to mention in my initial comment that I have fixed the telemetry section configuration for `statsite_address` and `statsd_address`. They were not put in `telemetry` section and was causing parsing failure. With this change we have added these properties in telemetry section.

**Pull request merged**
