### PR TITLE
Sanity test errand

### PR DESCRIPTION
**Pull request by drnic**
Status: errand fails trying to `vault write` to the `root` path. @jhunt ideas?

### CODE REVIEW

**Comment by jhunt** [comment]
In troubleshooting this, I'm noticing a few things about the broker itself:
- It doesn't handle HA vaults when the leader moves (at all)
- It doesn't seem to reconfigure when a new manifest is pushed changing the vault backend (I suspect bad job spec)

The work being done in https://github.com/starkandwayne/safe/issues/34 may provide some strategies for handling the HA leader moves.

Testing continues.

**Comment by jhunt** [comment]
I'm seeing two more things that are suspect:

```
[stderr]
+ export VAULT_ADDR=http://10.244.8.3:8200
+ VAULT_ADDR=http://10.244.8.3:8200
++ date +%s
++ rev
+ test_value=knock-9596531741
+ vault write secret/handshake sanity-test=knock-9596531741
++ vault read secret/handshake
++ grep sanity-test
++ awk '{print $2}'
+ read_value=knock-9596531741
+ [[ knock-9596531741 != \k\n\o\c\k\-\9\5\9\6\5\3\1\7\4\1 ]]
+ vault delete secret/handshake
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
+ main 64ef37bb-25c4-49e9-a847-eee27bde10e2 64ef37bb-25c4-49e9-a847-eee27bde10e2.shared T-9596531741 B-9596531741
```

curl is missing a URL somewhere, but I'm not sure where.

Also, manually trying to write to the path for the service, via the broker, using the token given, fails.  I'll file an issue against vault-broker itself to add tests, now that we know the `-dev` trick for getting an unsealed local in-memory vault spun up (the strategy we use for automated tests in safe)

**Comment by jhunt** [comment]
see https://github.com/cloudfoundry-community/vault-broker/issues/1

**Comment by drnic** [comment]
@jhunt fixed the bad curl (was just displaying the catalog)

**Pull request merged**
